services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: secret
    expose:
      - 54325
    ports:
      - 54325:5432

  adminer:
    image: adminer
    restart: always
