services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sunsave
      POSTGRES_PASSWORD: secret

  adminer:
    image: adminer
    restart: always
    expose:
      - 54325
    ports:
      - 127.0.0.1:54325:5432